In [1]:
import tensorflow as tf

In [2]:
sales_num = [21, 22, -108, 31, -1, 32, 34,31]
tfd = tf.data.Dataset.from_tensor_slices(sales_num)

In [3]:
tfd

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for num in tfd:
    print(num)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [5]:
for num in tfd:
    print(num.numpy())

21
22
-108
31
-1
32
34
31


In [6]:
tdr = tf.data.Dataset.list_files('reviews/*/*', shuffle=False)

In [7]:
def show(data):
    for i in tdr:
        print(i)

In [8]:
import os
len(tdr)

6

In [9]:
tdr = tdr.shuffle(5)

In [10]:
show(tdr)

tf.Tensor(b'reviews\\pos\\pos_1.txt', shape=(), dtype=string)
tf.Tensor(b'reviews\\neg\\neg_2.txt', shape=(), dtype=string)
tf.Tensor(b'reviews\\neg\\neg_3.txt', shape=(), dtype=string)
tf.Tensor(b'reviews\\neg\\neg_1.txt', shape=(), dtype=string)
tf.Tensor(b'reviews\\pos\\pos_2.txt', shape=(), dtype=string)
tf.Tensor(b'reviews\\pos\\pos_3.txt', shape=(), dtype=string)


In [11]:
class_ = ['pos','neg']

In [12]:
with open('reviews\\neg\\neg_2.txt') as f:
    content = f.read()
    print(content)

This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.<br /><br />It's truly disgraceful how far this show has fallen. The writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. I find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. How can one recognize such brilliance and then see fit to replace it with such mediocrity? I felt I must give 2 stars out of respect for the original cast that made this show such a huge success. As it is now, the show is just awful. I can't believe it's still on the air.


In [13]:
def get_label(file_path):
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[1]

In [14]:
get_label('reviews\\neg\\neg_2.txt')

<tf.Tensor: shape=(), dtype=string, numpy=b'neg'>

In [15]:
review_text = tf.io.read_file('reviews\\neg\\neg_2.txt') # load the raw data from the file as a string


In [16]:
review_text

<tf.Tensor: shape=(), dtype=string, numpy=b"This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.<br /><br />It's truly disgraceful how far this show has fallen. The writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. I find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. How can one recognize such brilliance and then see fit to replace it with such mediocrity? I felt I must give 2 stars out of respect for the original cast that made this show such a huge success. As it is now, the show is just awful. I can't believe it's still on the air.">

In [18]:
file_count = len(tdr)
file_count

6

In [19]:
train_size = int(file_count*0.8)
train_ds = tdr.take(train_size)
test_ds = tdr.skip(train_size)

In [28]:
def get_data(dataset):
    for path in dataset: 
        label = get_label(path)
        text = tf.io.read_file(path) # load the raw data from the file as a string
        return text, label

In [29]:
get_data(tdr)

(<tf.Tensor: shape=(), dtype=string, numpy=b''>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'neg'>)