# Numpy

In [1]:
import numpy as np
# rank 1 array
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
# it is 2D array
arr1 = np.array([[1,2,3,4],
                [5,6,7,8],
                [1.2,3.2,4,0],
                [10,11,23,56],
                [23,4.5,23,12]])
print(arr1)

[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.   8. ]
 [ 1.2  3.2  4.   0. ]
 [10.  11.  23.  56. ]
 [23.   4.5 23.  12. ]]


In [3]:
#making array with tuple
arr2 = np.array((1,2,3))
print(arr2)

[1 2 3]


In [4]:
# slicing of array : arr[row,col]
sl_arr1 = arr1[::2,::2]
print(sl_arr1)

[[ 1.   3. ]
 [ 1.2  4. ]
 [23.  23. ]]


In [5]:
#it will create arr of zeros
np.zeros(2)

array([0., 0.])

In [6]:
#it will create arr of ones
np.ones(3)

array([1., 1., 1.])

In [7]:
#it will create an empty arr with random values
np.empty(6)

array([ 1. ,  3. ,  1.2,  4. , 23. , 23. ])

In [8]:
# it will create array within range
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# it will create array within range
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [10]:
# it will create array within range with specified step
np.arange(4,10,2)

array([4, 6, 8])

In [11]:
# it will create array within range with specified number of element
np.linspace(2,20,num=4)

array([ 2.,  8., 14., 20.])

In [12]:
x=np.ones(3,dtype = np.int64)
print(x)
y = np.ones(3)
y  # by default dtype is float

[1 1 1]


array([1., 1., 1.])

In [13]:
from numpy import pi
x = np.linspace(0, 2 * pi, 10)        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [14]:
a= np.linspace(0,10,6,dtype = int)
print(a)
#adds number to every element
print(a+1)

[ 0  2  4  6  8 10]
[ 1  3  5  7  9 11]


In [15]:
ar = np.array([[1,2],[3,4]])
br = np.array([[5,6],[7,8]])
s = ar+4
print(s)
s == br

[[5 6]
 [7 8]]


array([[ True,  True],
       [ True,  True]])

In [16]:
br.sum() #sum of every element

26

In [17]:
ar = np.array([[1,2],[3,4]],np.int64)
br = np.array([[5,6],[7,8]])
print(ar+br)

[[ 6  8]
 [10 12]]


In [18]:
print(ar.dtype)

int64


In [19]:
print(ar.T) #transpose of array 

[[1 3]
 [2 4]]


In [20]:
print(ar)
print(np.sqrt(ar))

[[1 2]
 [3 4]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [22]:
br = np.array([[5,6],[7,8]])
print(br[1,0])
br[1,0] = 10 #changing the value
br

7


array([[ 5,  6],
       [10,  8]])

In [27]:
empty_like = np.empty_like(br)
print(empty_like)

[[5 6]
 [7 8]]


In [59]:
cr=np.arange(1,31)
cr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
np.shape(cr)

(30,)

In [61]:
cr=cr.reshape(3,10)
cr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [62]:
np.shape(cr) #Shape: The number of elements along with each axis. It is in form of tuple.

(3, 10)

In [66]:
cr = cr.ravel()  #it converts arr in 1D form

In [70]:
cr.shape 

(30,)

In [71]:
cr.nbytes #shows the total memory captured by an array

120

In [75]:
import sys
cr1 = [i for i in range (1,31)]
print(cr1)
print(sys.getsizeof(cr1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
336


In [80]:
cr=cr.reshape(3,10)
cr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [78]:
cr.sum(axis = 0)

array([33, 36, 39, 42, 45, 48, 51, 54, 57, 60])

In [79]:
cr.sum(axis = 1)

array([ 55, 155, 255])

In [81]:
cr.size # total number of element

30

In [82]:
cr.ndim # number of dimention

2

In [83]:
cr.argmax() #index having max value

29

In [100]:
cr.max() #max value in arr

30

In [88]:
cr[2]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [89]:
cr[2,5]

26

In [90]:
cr.nbytes

120

In [91]:
cr.argmin() #indax having minimum value

0

In [92]:
dr = np.array([[1,2,9],
               [3,4,10],
               [7,8,0]])

In [95]:
dr.sum(axis=0)

array([11, 14, 19])

In [96]:
dr.sum(axis=1)

array([12, 17, 15])

In [97]:
dr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [98]:
dr.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [99]:
dr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [102]:
li = [1,2,3,4]
tup = 5,6,7,8
np_li = np.array(li)
np_tup = np.array(tup)
print(np_li)
print(np_tup)

[1 2 3 4]
[5 6 7 8]


In [105]:
er = np.array([[1,2,3,4]])
er.ndim

2

In [106]:
np.linspace(3.5, 10, 3,dtype = np.int32)


array([ 3,  6, 10])

In [107]:
# way to create arr by fromiter
iterable = (a*a for a in range(8))
 
arr = np.fromiter(iterable, float)
 
print("fromiter() array :",arr)

fromiter() array : [ 0.  1.  4.  9. 16. 25. 36. 49.]


In [108]:
var = "prashant thakur"
 
arr = np.fromiter(var, dtype = 'U2')
 
print("fromiter() array :",arr)

fromiter() array : ['p' 'r' 'a' 's' 'h' 'a' 'n' 't' ' ' 't' 'h' 'a' 'k' 'u' 'r']


In [109]:
#creating full arr with specific number
np.full((3,4),8,dtype = 'complex')

array([[8.+0.j, 8.+0.j, 8.+0.j, 8.+0.j],
       [8.+0.j, 8.+0.j, 8.+0.j, 8.+0.j],
       [8.+0.j, 8.+0.j, 8.+0.j, 8.+0.j]])

In [114]:
er = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,0,1,2],
               [1,3,5,7]])
temp = er[[0,3]] # arr[[row],[col]] or a[i,j]
temp

array([[1, 2, 3, 4],
       [1, 3, 5, 7]])

In [115]:
temp = er[[0,1,2,3],[0,1,2,3]]
temp

array([1, 6, 1, 7])

In [120]:
er.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9,  9, 10, 12],
       [ 1,  4,  9, 16]], dtype=int32)

In [121]:
er.cumsum(axis=0) #cumulative sum

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15,  8, 11, 14],
       [16, 11, 16, 21]], dtype=int32)

In [122]:
fr = np.array([1,2,3,4,5,6])
for i in fr:
    print(i)

1
2
3
4
5
6


In [133]:
# array to list converter
list=[]
for i in np.nditer(er):
    p = i.tolist()
    list.append(p)
    
print(list,end="")

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 1, 3, 5, 7]

In [ ]:
# multiplication by element


In [134]:
ar = np.array([[1,2],[3,4]])
br = np.array([[5,6],[7,8]])
ar*br

array([[ 5, 12],
       [21, 32]])

In [135]:
#matrix multiplication
ar.dot(br)

array([[19, 22],
       [43, 50]])

In [141]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
print(l1+l2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [143]:
b=np.array(l1)
a=np.array(l2)
print(a*b)
print(a+b)

[ 5 12 21 32]
[ 6  8 10 12]


In [147]:
import array
hr = array.array('i',[1,2,3,4,5,6,7])
type(hr)

array.array

In [153]:
ir = np.empty(2)
ir = np.empty([2,3])
ir

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

In [166]:
jr = np.arange(8)
print(jr.ndim,"D")
jr

1 D


array([0, 1, 2, 3, 4, 5, 6, 7])

In [159]:
jr = np.arange(8).reshape(2,4)
print(jr.ndim)
jr

2


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [163]:
jr = np.arange(8).reshape(4,2)
print(jr.ndim,"D")
jr

2 D


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [162]:
jr = np.arange(8).reshape(2,2,2)
print(jr.ndim,"D")
jr

3 D


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])