In [4]:
import torch
import numpy as np

# Training Data

In [5]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [7]:
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [10]:
# convert array to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [11]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Linear regression model from scratch

In [27]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)


tensor([[ 1.1707, -0.5328,  1.1151],
        [ 0.4301,  0.3912, -0.1983]], requires_grad=True)
tensor([-0.8064,  0.8135], requires_grad=True)


In [28]:
def model(x):
    return x@w.t() + b
    

In [29]:
output=model(inputs)
output

tensor([[ 96.9056,  49.8886],
        [130.2064,  61.6794],
        [ 94.3264,  79.1433],
        [136.9503,  54.1620],
        [106.8805,  54.1575]], grad_fn=<AddBackward0>)

In [30]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Loss function

In [33]:
def loss(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [34]:
error = loss(output,targets)
error

tensor(2728.2180, grad_fn=<DivBackward0>)

In [60]:
def model(x):
    return x@w.t() + b

def loss(t1,t2):
        diff = t1-t2
        return torch.sum(diff*diff)/diff.numel()

for i in range(100):
    w = torch.randn(2,3,requires_grad=True)
    b = torch.randn(2,requires_grad=True)

    output=model(inputs)
    
    error = loss(output,targets)
    if error==100:
        break


print(error)
print(w)
print(b)

tensor(2393.9985, grad_fn=<DivBackward0>)
tensor([[ 0.3062,  0.0020,  0.0611],
        [ 0.8211,  0.4314, -0.4490]], requires_grad=True)
tensor([-0.7341,  0.1997], requires_grad=True)
