In [2]:
import numpy as np
a =3
b = 6
# does the bitwise operation on binary represantation of the array or variable
c = np.bitwise_and(a,b)
c

2

In [4]:
a = [1,2,3]
b= [4,5,-6]
c = np.bitwise_and(a,b)
c
# saame will be or , xor , invert(takes one arg) , right_sift(arg, bit_shift)

array([0, 0, 2], dtype=int32)

In [6]:
c = np.binary_repr(b[2],width=5)
c

'11010'

In [8]:
c = np.binary_repr(b[2])
c

'-110'

In [9]:
c = np.binary_repr(b[1],width=5)
c

'00101'

In [24]:
c = np.binary_repr(b[1])
c

'101'

In [29]:
d = np.array([[1,2,3,4],[5,6,7,6],[2,4,6,8],[3,5,7,9]],dtype=np.uint8)
e=np.packbits(d,axis=-1)
e

array([[240],
       [240],
       [240],
       [240]], dtype=uint8)

In [32]:
f = np.array([[2],[4],[56]],dtype = np.uint8)
e = np.unpackbits(f,axis=1)
e

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0]], dtype=uint8)

String operation

In [33]:
b = np.array(["PRASHANT",'THAKUR'])
np.char.lower(b)

array(['prashant', 'thakur'], dtype='<U8')

In [37]:
np.char.lower("THAKUR")

array('thakur', dtype='<U6')

In [40]:
# Python program explaining
# numpy.rfind() function
 
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.rfind(a,'gee'))
 
# counting a substring
print(np.char.rfind(a, 'fo'))

[ 0 -1  0]
[-1  0 -1]
