In [11]:
import numpy as np
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
for i in np.nditer(a):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [16]:
a.T
for i in np.nditer(a):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [20]:
print(a.T)
for i in np.nditer(a,order='F'): # Horizontally
    print(i, end=" ")

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
0 5 1 6 2 7 3 8 4 9 

In [19]:
print(a.T)
for i in np.nditer(a,order='C'):  # Vertically
    print(i, end=" ")

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
0 1 2 3 4 5 6 7 8 9 

In [21]:
print(a)
# modifying array value
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 5*x
print('Modified array is:')
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
Modified array is:
[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [26]:
for x in np.nditer(a,flags = ['external_loop'],order='F'):
    print(x)

[ 0 25]
[ 5 30]
[10 35]
[15 40]
[20 45]


Broadcasting

In [29]:
f = np.array([[1,2,3],[4,5,6]])
f.shape

(2, 3)

In [30]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

a + b  # Output: array([[11, 22, 33], [14, 25, 36]])


array([[11, 22, 33],
       [14, 25, 36]])