In [4]:
import numpy as np
a = np.array([[4,6,8],[2,4,5],[4,4,5]])
print(np.linalg.matrix_rank(a))

3


In [5]:
np.trace(a)

13

In [8]:
np.linalg.det(a)

-3.999999999999999

In [9]:
np.linalg.inv(a)

array([[ 0. , -0.5,  0.5],
       [-2.5,  3. ,  1. ],
       [ 2. , -2. , -1. ]])

In [10]:
print(np.linalg.eigh(a))

(array([-0.17890835,  2.        , 11.17890835]), array([[ 4.77481651e-01,  7.07106781e-01, -5.21546999e-01],
       [ 4.77481651e-01, -7.07106781e-01, -5.21546999e-01],
       [-7.37578840e-01, -2.22044605e-16, -6.75261027e-01]]))


In [11]:
print(np.linalg.eig(a))

(array([13.56789831, -0.89668127,  0.32878297]), array([[-0.72235928, -0.53000001,  0.22101101],
       [-0.43282964, -0.49013243, -0.82619501],
       [-0.53931028,  0.69200447,  0.51822383]]))


In [12]:
va = 2 + 3j
vb = 4 + 5j
np.dot(va,vb)

(-7+22j)

In [13]:
np.vdot(va,vb)

(23-2j)